export const genres: string[] = ['comedy', 'documentary', 'horror', 'crime'];
export const sortOptions: string[] = ['Release date', 'Name', 'Rating'];
export const movies: any[] = [
  {
    id: 1,
    title: 'Rudolph the Red-Nosed Reindeer: The Movie',
    releaseDate: 2012,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 2,
    title: 'Citizen, The',
    releaseDate: 2003,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 3,
    title: 'Ring Two, The',
    releaseDate: 2002,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 4,
    title: 'Torque',
    releaseDate: 1992,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 5,
    title: 'D.C. Cab',
    releaseDate: 2007,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Crime'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 6,
    title: 'Women, The',
    releaseDate: 1999,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 7,
    title: 'Destroy All Monsters (Kaijû sôshingeki)',
    releaseDate: 2005,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 8,
    title: 'Piter FM',
    releaseDate: 2004,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Crime'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 9,
    title: 'Defenders of Riga',
    releaseDate: 1992,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 10,
    title: 'Israeli Intelligence (Hamosad Hasagur)',
    releaseDate: 2004,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 11,
    title: 'Show People',
    releaseDate: 2008,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 12,
    title: 'Let the Right One In (Låt den rätte komma in)',
    releaseDate: 2001,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
];
