export const genres: string[] = ['comedy', 'documentary', 'horror', 'crime'];
export const sortOptions: string[] = ['Release date', 'Name', 'Rating'];
export const movies: any[] = [
  {
    id: 1,
    title: 'Rudolph the Red-Nosed Reindeer: The Movie',
    releaseDate: 2012,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 2,
    title: 'Citizen, The',
    releaseDate: 2003,
    posterPath: '/assets/coming_soon.png',
    overview: 'Abdullah runs a motorcycle workshop with a few workers. He also gives casual legal advises to the locals. A computer science student named Indhu develops a crush on him and tries woo him, although Abdullah has nothing of it.\n'
        + '\n'
        + 'In a massive street protest by lawyers across the city, Abdullah, in altered appearance, kidnaps Judge Vedhachalam, after introducing himself as ‘Citizen’. Later on, Abdullah proceeds to kidnap Collector Santhanam by posing as freedom fighter Sundaramoorthy. In both kidnaps, Abdullah mentions ‘Attipatti’, which seemed to render his victims speechless.\n'
        + '\n'
        + 'With these two high-profile kidnappings, the case is handed over to CBI, led by Senior Officer Sarojini Harichandran. Sarojini finds out that both kidnap victims worked together in Mayavaram division some years ago, and was involved in a riot that happened in Attipatti. However, a check with Mailadhurai sub-collector’s office and Nagapattinam collector’s office found that there is no town or village in the area named Attipatti. She then visits the main collector’s office in Tanjavur and is shocked to find out that the village Attipatti existed in records before 1973, but not in the years after that. She becomes certain that the kidnapper too has a link to Attipatti.\n'
        + '\n'
        + 'Meanwhile, Abdullah becomes irritated with Indhu who keeps longing for his affection. He scolds her and says that she doesn’t know who he really is and the pain he endures in his heart.',
    genres: ['Comedy'],
    voteAverage: 4.3,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 3,
    title: 'Ring Two, The',
    releaseDate: 2002,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 4,
    title: 'Torque',
    releaseDate: 1992,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 5,
    title: 'D.C. Cab',
    releaseDate: 2007,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Crime'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 6,
    title: 'Women, The',
    releaseDate: 1999,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 7,
    title: 'Destroy All Monsters (Kaijû sôshingeki)',
    releaseDate: 2005,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror', 'Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 8,
    title: 'Piter FM',
    releaseDate: 2004,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Crime'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 9,
    title: 'Defenders of Riga',
    releaseDate: 1992,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 10,
    title: 'Israeli Intelligence (Hamosad Hasagur)',
    releaseDate: 2004,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Documentary'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 11,
    title: 'Show People',
    releaseDate: 2008,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Comedy'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
  {
    id: 12,
    title: 'Let the Right One In (Låt den rätte komma in)',
    releaseDate: 2001,
    posterPath: '/assets/coming_soon.png',
    overview: 'Some text',
    genres: ['Horror'],
    voteAverage: 5,
    voteCount: 10,
    budget: 10000,
    revenue: 50000,
    runtime: 120,
    tagline: 'tagline',
  },
];
